"""empty message

<<<<<<<< HEAD:migrations/versions/2ad856c7c78b_.py
Revision ID: 2ad856c7c78b
Revises: 
Create Date: 2023-01-28 17:44:02.810561
========
Revision ID: 2c81c9da4003
Revises: 
Create Date: 2023-01-28 14:40:20.220847
>>>>>>>> e54b90dcb8be0ccd530e5d8be41f25b160fb7f71:migrations/versions/2c81c9da4003_.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:migrations/versions/2ad856c7c78b_.py
revision = '2ad856c7c78b'
========
revision = '2c81c9da4003'
>>>>>>>> e54b90dcb8be0ccd530e5d8be41f25b160fb7f71:migrations/versions/2c81c9da4003_.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
<<<<<<<< HEAD:migrations/versions/2ad856c7c78b_.py
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=1000), nullable=False),
========
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item', sa.String(length=50), nullable=False),
>>>>>>>> e54b90dcb8be0ccd530e5d8be41f25b160fb7f71:migrations/versions/2c81c9da4003_.py
    sa.Column('img_url', sa.String(length=1000), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('img_url'),
    sa.UniqueConstraint('item_name'),
    sa.UniqueConstraint('price')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cart',
<<<<<<<< HEAD:migrations/versions/2ad856c7c78b_.py
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.item_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
========
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('cart_id')
>>>>>>>> e54b90dcb8be0ccd530e5d8be41f25b160fb7f71:migrations/versions/2c81c9da4003_.py
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    op.drop_table('user')
    op.drop_table('product')
    # ### end Alembic commands ###
