"""empty message

Revision ID: 75bd4cc77371
Revises: 211c20be954b
Create Date: 2023-01-27 14:50:44.864210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75bd4cc77371'
down_revision = '211c20be954b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.String(), nullable=False))
        batch_op.drop_constraint('addproduct_item_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'product', ['item_name'], ['item'])
        batch_op.drop_column('item')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addproduct', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('addproduct_item_fkey', 'product', ['item'], ['item'])
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
